#lang racket/load
;(require trace)

#| Problem 1
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.
|#

(define (divisible n d)
  (= 0 (remainder n d)))

(define (multiple-3-5 n)
  (or (divisible n 3)
      (divisible n 5)))

(define (sum-natural limit)
  (define (itr-sum result next)
    (cond ((>= next limit)
           result)
          ((multiple-3-5 next)
           (itr-sum (+ result next) (+ next 1)))
          (else (itr-sum result (+ next 1)))))
  (itr-sum 0 1))

#| Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
|#

(define (fib n)
  (define (fib-itr n-1 n count)
    (if (= count 0)
        n
        (fib-itr n (+ n-1 n) (- count 1))))
  (if (<= n 2)
      n
      (fib-itr 0 1 n)))

(define (fib-seq limit)
  (define (fib-list n)
      (if (> (fib n) limit)
          '()
          (cond ((even? (fib n))
                 (cons (fib n) (fib-list (+ n 1))))
                (else (fib-list (+ n 1))))))
  (fib-list 1))

(define (sum-list list)
  (define (sum-itr list sum)
    (if (null? list)
        sum
        (sum-itr (cdr list) (+ (car list) sum))))
  (sum-itr list 0))

(define (even-fib-sum limit)
  (sum-list (fib-seq limit)))

#| Problem 3
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143?
|#

; Divide n by 2.
  ;If it divides, check if result is prime.
   ;If result is prime then return it
   ;If not prime, divide it by 2.
  ;If it doesn't divide, divide by the next prime

(define (divides? n divisor)
  (= 0 (remainder n divisor)))

(define (second-factor n divisor)
  (/ n divisor))

(define (largest-factor n)
  (define (factor-itr n test)
    (if (divides? n test)
        (second-factor n test)
        (factor-itr n (+ test 1))))
  (factor-itr n 2))

(define (prime? n)
  (if (= n 1)
      false
      (= (largest-factor n) 1)))

(define (largest-prime-factor n)
  (define (prime-factor-itr n test)
          (if (and (divides? n test) (prime? (second-factor n test)))
              (second-factor n test)
              (prime-factor-itr n (+ test 1))))
  (if (prime? n)
      n
      (prime-factor-itr n 2)))

#| Problem 4
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.
|#

(define (reversed-number-to-list n)
  (if (< n 10)
      (list n)
      (cons (remainder n 10)
            (reversed-number-to-list (quotient n 10)))))

(define (reverse-list l)
  (define (iter list reversed)
    (if (null? list)
      reversed
      (iter (cdr list) (cons (car list) reversed))))
  (iter l '()))

(define (palindrome? n)
  (equal? (reversed-number-to-list n) (reverse-list (reversed-number-to-list n))))

;Evaluate (largest-palindrome 100 1000) for the answer
(define (largest-palindrome a b)
  (let* ((range1 (range a b))
         (range2 (range a b))
         (products (apply append
                          (map (lambda (x)
                                 (map (lambda (y)
                                        (* x y))
                                      range2))
                               range1))))
    (define (largest-pali ab result)
      (cond ((null? ab)
             result)
            ((and (> (car ab) result)
                  (palindrome? (car ab)))
             (largest-pali (cdr ab) (car ab)))
            (else
             (largest-pali (cdr ab) result))))
    (largest-pali products 0)))

#| Problem 5
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
|#

(define (divide-by-all-numbers number range)
  (if (null? range)
      true
      (cond ((divides? number (car range))
             (divide-by-all-numbers number (cdr range)))
            (else
             false))))

(define (smallest-number test)
  (let ((numbers '(11 13 14 16 17 18 19 20)))
    (if (divide-by-all-numbers test numbers)
        test
        (smallest-number (+ test 20)))))

#| Problem 6
The sum of the squares of the first ten natural numbers is 385.
The square of the sum of the first ten natural numbers is 3025.

Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
|#

(define (square x) (* x x))

(define (sum-squares range)
  (apply
   +
   (map (lambda (x)
          (square x))
        range)))

(define (square-sum range)
  (square
   (apply + range)))

(define (diff-sumsquares-squaresum range)
  (- (square-sum range) (sum-squares range)))

#| Problem 7
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?
|#

(define (nth-prime n)
  (define (iter count number prime)
    (if (>= count n)
        prime
        (cond ((prime? number)
               (iter (+ count 1) (+ number 1) number))
              (else
               (iter count (+ number 1) prime)))))
  (iter 0 0 0))

#| Problem 8

The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
|#

(define (first-n n l)
  (if (or (zero? n) (null? l))
      '()
      (cons (car l) (first-n (- n 1) (cdr l)))))

(define (product-list l)
  (apply * l))

(define (number-to-list n)
  (reverse-list (reversed-number-to-list n)))

(define (max-product-digits number n)
  (let ((numlist (number-to-list number)))
    (define (iter digits max)
      (let*
          ((adjacent (first-n n digits))
           (adjacent-product (product-list adjacent)))
        (cond ((< (length adjacent) n)
               max)
              ((> adjacent-product max)
               (iter (cdr digits) adjacent-product))
              (else (iter (cdr digits) max)))))
    (iter numlist 0)))

#| Problem 9

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a^2 + b^2 = c^2
For example, 32 + 42 = 9 + 16 = 25 = 5^2.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

|#

(define (euclid-triplets n m)
  (if (> n m)
      (print "Error, n is great than m")
      (list (- (square m) (square n)) (* 2 m n) (+ (square m) (square n)))))

(define (sum-triplets abc)
  (sum-list abc))

(define (product-triplets abc)
  (apply * abc))

(define (find-sum-triplets total)
  (define (itr n m)
    (cond ((= total (sum-triplets (euclid-triplets n m)))
           (list (product-triplets (euclid-triplets n m)) (euclid-triplets n m)))
          ((> (sum-triplets (euclid-triplets n m)) total)
           (itr (+ 1 n) (+ 2 n)))
          (else (itr n (+ 1 m)))))
  (itr 1 2))

        
  
      

